# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f80189aa9d454c996c42260d9e16dfa8e26acb916dc61f6d7b0d3c17ecf3cf990df2168ebadc4068a82f45f0924014f72e572373e1b6219c59ab19bbf1c2360

test:
  secret_key_base: 55a71925f9fb00acc181b003a7056f2e4e5bb8b6dee4b0723e7cfaf4caeae346fe198cfee8746b737f48d2ae3953b514fba71b24336c2dabece14dc68fcbcced

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
